### ISSUE TITLE
Story Menu assets aren't loading

### ISSUE THREAD

**Issue by GiffanyCD** [Psych-Slice/P-Slice#70] opened 2024-11-11 06:05 UTC
### Describe your bug here.

So I go port this mod I'm working on over, and like story mode is just missing assets, even though they are in the right folder to my knowledge

I don't know what's going on, I need help
![help](https://github.com/user-attachments/assets/4d7ca0c3-83a2-413d-9d53-5958750df065)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I just copied assets from the Psych Engine 7.3 build to P-slice

**Comment by moxie-coder** [comment] 2024-11-11 06:58
yeah I think that might be why
![IMG_6081](https://github.com/user-attachments/assets/1c1dbbf7-4015-46a0-899e-2182274d0aae)

**Comment by GiffanyCD** [comment] 2024-11-11 19:11
shit, don't tell me I have to reprogram everything...

**Comment by mikolka9144** [comment] 2024-11-12 06:51
Closing this as the issue was likely caused by the user

**Closed by mikolka9144** 2024-11-12 06:51 UTC
Labels: bug

**Comment by GiffanyCD** [comment] 2024-11-12 19:00
well it's fixed now
